/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.wireless.web.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.actions.DispatchAction;

import com.wireless.entity.Tabletbl;
import com.wireless.web.forms.TableForm;
import com.wirelsee.web.service.TableService;

/** 
 * MyEclipse Struts
 * Creation date: 08-29-2013
 * 
 * XDoclet definition:
 * @struts.action parameter="flag" validate="true"
 */
public class TableAction extends DispatchAction {
	
	private TableService tableService;
	
	public TableService getTableService() {
		return tableService;
	}

	public void setTableService(TableService tableService) {
		this.tableService = tableService;
	}

	//返回table页
	public ActionForward table(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		
		/* 
		 * 判断用户所点击的当前页数
		 * 若无点击，则默认第一页
		 */
		String s_pageNow=request.getParameter("pageNow"); 
		int pageNow=1;
		if(s_pageNow!=null){
			pageNow=Integer.parseInt(s_pageNow);
		}
		//默认一页存放5条数据
		//获得总页数
		int pageCount=tableService.getPageCount(5);
		//判断是否存在前一页后一页
		String pre="no";
		String next="no";
		if(pageNow!=1){
			pre="yes";
		}
		if(pageNow!=pageCount){
			next="yes";
		}
		request.setAttribute("pNow", pageNow);
		request.setAttribute("pre", pre);
		request.setAttribute("next", next);
		//向数据库查询Table对象，放入session中
		request.setAttribute("tablelist", tableService.getTableList(pageNow, 5));
		request.setAttribute("pageCount", pageCount);
		return mapping.findForward("table");
	}
	//返回桌子修改页面
	public ActionForward tableEdit(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		Integer id=Integer.parseInt(request.getParameter("id"));
		Tabletbl tbl=tableService.getATable(id);
		request.setAttribute("tbl", tbl);
		return mapping.findForward("tableEdit");
	}
	//
	public ActionForward updTable(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		TableForm tableForm=(TableForm)form;
		
		//
		Tabletbl table=new Tabletbl();
		table.setId(tableForm.getTid());
		table.setOrdId(tableForm.getOrdId());
		table.setDescription(tableForm.getDescription());
		table.setFlag(tableForm.getTflag());
		table.setNum(tableForm.getNum());
		
		if(tableService.updTable(table)){
			request.setAttribute("tbl", table);
			request.setAttribute("updtbl", "yes");
			return mapping.findForward("tableEdit");
		}else{
			return mapping.findForward("tableEdit");
		}
	}
	//
	public ActionForward delTable(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		String delid=request.getParameter("delid");
		if(delid!=null){
			tableService.delTable(Integer.parseInt(delid));
		}
		String s_pageNow=request.getParameter("pageNow"); 
		int pageNow=1;
		if(s_pageNow!=null){
			pageNow=Integer.parseInt(s_pageNow);
		}
		int pageCount=tableService.getPageCount(5);
		//判断是否存在前一页后一页
		String pre="no";
		String next="no";
		if(pageNow!=1){
			pre="yes";
		}
		if(pageNow!=pageCount){
			next="yes";
		}
		request.setAttribute("pNow", pageNow);
		request.setAttribute("pre", pre);
		request.setAttribute("next", next);
		request.setAttribute("tablelist", tableService.getTableList(pageNow, 5));
		request.setAttribute("pageCount", pageCount);
		return mapping.findForward("table");
	}
	public ActionForward addTable(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		//
		TableForm tableForm=(TableForm)form;
		Tabletbl table=new Tabletbl();
		table.setDescription("无");
		table.setFlag("1");
		table.setNum(tableForm.getNum());
		System.out.println(table.getNum());
		table.setOrdId(0);
		if(tableService.addTable(table)){
			request.setAttribute("addtable", "yes");
		}
		//
		String s_pageNow=request.getParameter("pageNow"); 
		int pageNow=1;
		if(s_pageNow!=null){
			pageNow=Integer.parseInt(s_pageNow);
		}
		int pageCount=tableService.getPageCount(5);
		//判断是否存在前一页后一页
		String pre="no";
		String next="no";
		if(pageNow!=1){
			pre="yes";
		}
		if(pageNow!=pageCount){
			next="yes";
		}
		request.setAttribute("pNow", pageNow);
		request.setAttribute("pre", pre);
		request.setAttribute("next", next);
		request.setAttribute("tablelist", tableService.getTableList(pageNow, 5));
		request.setAttribute("pageCount", pageCount);
		return mapping.findForward("table");
	}
}