/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.wireless.web.forms;

import org.apache.struts.action.ActionForm;

import com.wireless.entity.Menutbl;
import com.wireless.entity.Ordertbl;
import com.wireless.entity.Tabletbl;

/** 
 * MyEclipse Struts
 * Creation date: 09-22-2013
 * 
 * XDoclet definition:
 * @struts.form name="orderForm"
 */
public class OrderForm extends ActionForm {
	//订单表
	private Integer o_id;
	private String orderTime;
	private Integer userId;
	private Integer personNum;
	private Integer idPay;
	private String o_remark;     //
	private Tabletbl tabletbl;//外键--tableID
	private Integer tableID;
	
	//订单明细表
	private Integer od_id;
	private Menutbl menutbl; 	 //外键menuID
	private Integer menuID;
	private Ordertbl ordertbl;		 //外键orderID
	private Integer orderID;
	private Integer num;             
	private String od_remark;
	
	public Integer getO_id() {
		return o_id;
	}
	public void setO_id(Integer o_id) {
		this.o_id = o_id;
	}
	public String getOrderTime() {
		return orderTime;
	}
	public void setOrderTime(String orderTime) {
		this.orderTime = orderTime;
	}
	public Integer getUserId() {
		return userId;
	}
	public void setUserId(Integer userId) {
		this.userId = userId;
	}
	public Integer getPersonNum() {
		return personNum;
	}
	public void setPersonNum(Integer personNum) {
		this.personNum = personNum;
	}
	public Integer getIdPay() {
		return idPay;
	}
	public void setIdPay(Integer idPay) {
		this.idPay = idPay;
	}
	public String getO_remark() {
		return o_remark;
	}
	public void setO_remark(String o_remark) {
		this.o_remark = o_remark;
	}
	public Tabletbl getTabletbl() {
		return tabletbl;
	}
	public void setTabletbl(Tabletbl tabletbl) {
		this.tabletbl = tabletbl;
	}
	public Integer getOd_id() {
		return od_id;
	}
	public void setOd_id(Integer od_id) {
		this.od_id = od_id;
	}
	public Menutbl getMenutbl() {
		return menutbl;
	}
	public void setMenutbl(Menutbl menutbl) {
		this.menutbl = menutbl;
	}
	public Ordertbl getOrdertbl() {
		return ordertbl;
	}
	public void setOrdertbl(Ordertbl ordertbl) {
		this.ordertbl = ordertbl;
	}
	public Integer getNum() {
		return num;
	}
	public void setNum(Integer num) {
		this.num = num;
	}
	public String getOd_remark() {
		return od_remark;
	}
	public void setOd_remark(String od_remark) {
		this.od_remark = od_remark;
	}
	public Integer getTableID() {
		return tableID;
	}
	public void setTableID(Integer tableID) {
		this.tableID = tableID;
	}
	public Integer getMenuID() {
		return menuID;
	}
	public void setMenuID(Integer menuID) {
		this.menuID = menuID;
	}
	public Integer getOrderID() {
		return orderID;
	}
	public void setOrderID(Integer orderID) {
		this.orderID = orderID;
	}
	
	
}