/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.wireless.web.forms;

import org.apache.struts.action.ActionForm;

/** 
 * MyEclipse Struts
 * Creation date: 09-22-2013
 * 
 * XDoclet definition:
 * @struts.form name="orderDetailForm"
 */
public class OrderDetailForm extends ActionForm {
}