/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.wireless.web.forms;

import org.apache.struts.action.ActionForm;

/** 
 * MyEclipse Struts
 * Creation date: 09-04-2013
 * 
 * XDoclet definition:
 * @struts.form name="tableForm"
 */
public class TableForm extends ActionForm {
	// Fields

		private Integer tid;
		private Integer ordId;
		private String num;
		private String tflag;
		private String description;
		public Integer getTid() {
			return tid;
		}
		public void setTid(Integer tid) {
			this.tid = tid;
		}
		public Integer getOrdId() {
			return ordId;
		}
		public void setOrdId(Integer ordId) {
			this.ordId = ordId;
		}
		public String getNum() {
			return num;
		}
		public void setNum(String num) {
			this.num = num;
		}
		
		public String getTflag() {
			return tflag;
		}
		public void setTflag(String tflag) {
			this.tflag = tflag;
		}
		public String getDescription() {
			return description;
		}
		public void setDescription(String description) {
			this.description = description;
		}
		
}